### ISSUE TITLE
Results not the same as in referenced paper

### ISSUE THREAD

**Issue by timmolter** [MartyMacGyver/memristor-modeling#1]
Hi, just wondering if you noticed that the results are not the same as in the referenced paper Figure 5. From what I can tell all the model params and simulation are identical to Figure 5 A. The only thing I can think of is they used PSPICE perhaps and for some reason that causes a difference? Any ideas?

BTW, thanks for posting this. It helped me a lot!

![screen shot 2016-09-26 at 5 14 11 pm](https://cloud.githubusercontent.com/assets/738972/18839882/e3e6ce84-840c-11e6-9645-3206640ffeda.png)
![screen shot 2016-09-26 at 5 11 25 pm](https://cloud.githubusercontent.com/assets/738972/18839881/e3d97df6-840c-11e6-99b4-fd159f10e570.png)

**Comment by timmolter** [comment]
Never mind. I figured it out. If you set `p=1` it comes out the same as in the paper. The paper has a typo I guess.

**Comment by MartyMacGyver** [comment]
Good catch! I'm re-opening this as I wonder how best to call this out in the documentation (or whether there's a way to make that parameter readily modified by the user).
