### ISSUE TITLE
Circuit design of memristor

### ISSUE THREAD

**Issue by 1477qq** [MartyMacGyver/memristor-modeling#3]
Hello, I am also doing research on memristors now, but I have encountered a lot of problems in the circuit design process of neural network based on memristor array. I see that you are also doing related research here and would like to ask you some questions. I hope you can give me some contact information.

**Comment by MartyMacGyver** [comment]
I'd like to help but I'm not a researcher, just a hobbyist.... therefore I don't have much to offer beyond what's here.

**Comment by 1477qq** [comment]
It doesn't matter. Thank you for your reply.
